name: Build Resumé and release

on: [push]

jobs:
  build_and_release_resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: phelipe_teles.tex
          pre_compile: tlmgr install calcage

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date '+%Y%m%d%H%M')"

      - name: Create tag
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: ${{ steps.date.outputs.date }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: phelipe_teles.pdf
          tag_name: ${{ steps.date.outputs.date }}
